# Exploratory Data Analysis of online retail transacaction data

In [225]:
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats

In [226]:
source_link = "https://archive.ics.uci.edu/dataset/502/online+retail+ii"

In [227]:
df = pd.read_csv("C:\\Desktop\\Online retail UnsML k-mean analysis\\data\\raw data\\online_retail_II.csv")
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,1/12/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,1/12/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,1/12/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,1/12/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,1/12/2010 8:26,3.39,17850.0,United Kingdom

# Data Exploration

walk through each columns of data and check the data details before futher feature engeering

In [228]:
df.info()
df.shape

<class 'pandas.DataFrame'>
RangeIndex: 541910 entries, 0 to 541909
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      541910 non-null  str
 1   StockCode    541910 non-null  str
 2   Description  540456 non-null  str
 3   Quantity     541910 non-null  int64
 4   InvoiceDate  541910 non-null  str
 5   Price        541910 non-null  float64
 6   Customer ID  406830 non-null  float64
 7   Country      541910 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 33.1 MB

(541910, 8)

In [229]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Quantity,541910.0,9.552234,218.080957,-80995.00,1.00,3.00,10.00,80995.0
Price,541910.0,4.611138,96.759765,-11062.06,1.25,2.08,4.13,38970.0
Customer ID,406830.0,15287.684160,1713.603074,12346.00,13953.00,15152.00,16791.00,18287.0

In [230]:
df.select_dtypes(include=["object"]).describe().T

C:\Users\User\AppData\Local\Temp\ipykernel_15708\2317286653.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include=["object"]).describe().T

              count unique                                 top    freq
Invoice      541910  25900                              573585    1114
StockCode    541910   4070                              85123A    2313
Description  540456   4223  WHITE HANGING HEART T-LIGHT HOLDER    2369
InvoiceDate  541910  23260                    31/10/2011 14:41    1114
Country      541910     38                      United Kingdom  495478

In [231]:
print(df.duplicated().sum())

5268

In [232]:
df[df.duplicated(keep='first')].sort_values(by=df.columns.tolist())

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,1/12/2010 11:45,1.25,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,1/12/2010 11:45,4.95,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,1/12/2010 11:45,2.10,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,1/12/2010 11:45,2.95,17908.0,United Kingdom
598,536412,21448,12 DAISY PEGS IN WOOD BOX,1,1/12/2010 11:49,1.65,17920.0,United Kingdom
...,...,...,...,...,...,...,...,...
411644,C572226,85066,CREAM SWEETHEART MINI CHEST,-1,21/10/2011 13:58,12.75,15321.0,United Kingdom
436251,C574095,22326,ROUND SNACK BOXES SET OF4 WOODLAND,-1,3/11/2011 9:54,2.95,12674.0,France
440149,C574510,22360,GLASS JAR ENGLISH CONFECTIONERY,-1,4/11/2011 13:25,2.95,15110.0,United Kingdom
461408,C575940,23309,SET OF 60 I LOVE LONDON CAKE CASES,-24,13/11/2011 11:38,0.55,17838.0,United Kingdom
529981,C580764,22667,RECIPE BOX RETROSPOT,-12,6/12/2011 10:38,2.95,14562.0,United Kingdom

In [233]:
df[df.duplicated(keep=False)].sort_values(by=df.columns.tolist())
# This keep = False shows 13,283 rows that each have at least one duplicate,
# some row may appear more than twice

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
494,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,1/12/2010 11:45,1.25,17908.0,United Kingdom
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,1/12/2010 11:45,1.25,17908.0,United Kingdom
485,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,1/12/2010 11:45,4.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,1/12/2010 11:45,4.95,17908.0,United Kingdom
489,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,1/12/2010 11:45,2.10,17908.0,United Kingdom
...,...,...,...,...,...,...,...,...
440149,C574510,22360,GLASS JAR ENGLISH CONFECTIONERY,-1,4/11/2011 13:25,2.95,15110.0,United Kingdom
461407,C575940,23309,SET OF 60 I LOVE LONDON CAKE CASES,-24,13/11/2011 11:38,0.55,17838.0,United Kingdom
461408,C575940,23309,SET OF 60 I LOVE LONDON CAKE CASES,-24,13/11/2011 11:38,0.55,17838.0,United Kingdom
529980,C580764,22667,RECIPE BOX RETROSPOT,-12,6/12/2011 10:38,2.95,14562.0,United Kingdom
529981,C580764,22667,RECIPE BOX RETROSPOT,-12,6/12/2011 10:38,2.95,14562.0,United Kingdom

In [234]:
print("Null number:\n",df.isnull().sum())

Null number:
 Invoice             0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
Price               0
Customer ID    135080
Country             0
dtype: int64

In [235]:
df[df["Customer ID"].isnull()].head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
622,536414,22139,NaN,56,1/12/2010 11:52,0.00,NaN,United Kingdom
1443,536544,21773,DECORATIVE ROSE BATHROOM BOTTLE,1,1/12/2010 14:32,2.51,NaN,United Kingdom
1444,536544,21774,DECORATIVE CATS BATHROOM BOTTLE,2,1/12/2010 14:32,2.51,NaN,United Kingdom
1445,536544,21786,POLKADOT RAIN HAT,4,1/12/2010 14:32,0.85,NaN,United Kingdom
1446,536544,21787,RAIN PONCHO RETROSPOT,2,1/12/2010 14:32,1.66,NaN,United Kingdom
1447,536544,21790,VINTAGE SNAP CARDS,9,1/12/2010 14:32,1.66,NaN,United Kingdom
1448,536544,21791,VINTAGE HEADS AND TAILS CARD GAME,2,1/12/2010 14:32,2.51,NaN,United Kingdom
1449,536544,21801,CHRISTMAS TREE DECORATION WITH BELL,10,1/12/2010 14:32,0.43,NaN,United Kingdom
1450,536544,21802,CHRISTMAS TREE HEART DECORATION,9,1/12/2010 14:32,0.43,NaN,United Kingdom
1451,536544,21803,CHRISTMAS TREE STAR DECORATION,11,1/12/2010 14:32,0.43,NaN,United Kingdom

In [236]:
df[df["Description"].isnull()].head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
622,536414,22139,NaN,56,1/12/2010 11:52,0.0,NaN,United Kingdom
1510,536545,21134,NaN,1,1/12/2010 14:32,0.0,NaN,United Kingdom
1985,536547,37509,NaN,1,1/12/2010 14:33,0.0,NaN,United Kingdom
1986,536546,22145,NaN,1,1/12/2010 14:33,0.0,NaN,United Kingdom
2022,536552,20950,NaN,1,1/12/2010 14:34,0.0,NaN,United Kingdom
2023,536549,85226A,NaN,1,1/12/2010 14:34,0.0,NaN,United Kingdom
2024,536550,85044,NaN,1,1/12/2010 14:34,0.0,NaN,United Kingdom
2025,536553,37461,NaN,3,1/12/2010 14:35,0.0,NaN,United Kingdom
2026,536554,84670,NaN,23,1/12/2010 14:35,0.0,NaN,United Kingdom
2406,536589,21777,NaN,-10,1/12/2010 16:50,0.0,NaN,United Kingdom

In [237]:
df[df["Quantity"]<0].head(10)
# quantity with <0 means cancel as the invoice number start with c

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
141,C536379,D,Discount,-1,1/12/2010 9:41,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,1/12/2010 9:49,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,1/12/2010 10:24,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,1/12/2010 10:24,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,1/12/2010 10:24,0.29,17548.0,United Kingdom
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,1/12/2010 10:24,0.29,17548.0,United Kingdom
239,C536391,21484,CHICK GREY HOT WATER BOTTLE,-12,1/12/2010 10:24,3.45,17548.0,United Kingdom
240,C536391,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,1/12/2010 10:24,1.65,17548.0,United Kingdom
241,C536391,22553,PLASTERS IN TIN SKULLS,-24,1/12/2010 10:24,1.65,17548.0,United Kingdom
937,C536506,22960,JAM MAKING SET WITH JARS,-6,1/12/2010 12:38,4.25,17897.0,United Kingdom

In [238]:
df["Invoice"] = df["Invoice"].astype("str") # Use regex to catch anomaly in columns , regex only can run on str so convert to str first
df[df["Invoice"].str.match("^\\d{6}$")==False] # catch anomaly 
# these 2 line are to show the invoice with c letterstand for cancellation

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
141,C536379,D,Discount,-1,1/12/2010 9:41,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,1/12/2010 9:49,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,1/12/2010 10:24,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,1/12/2010 10:24,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,1/12/2010 10:24,0.29,17548.0,United Kingdom
...,...,...,...,...,...,...,...,...
540449,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,9/12/2011 9:57,0.83,14397.0,United Kingdom
541541,C581499,M,Manual,-1,9/12/2011 10:28,224.69,15498.0,United Kingdom
541715,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,9/12/2011 11:57,10.95,15311.0,United Kingdom
541716,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,9/12/2011 11:58,1.25,17315.0,United Kingdom
541717,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,9/12/2011 11:58,1.25,17315.0,United Kingdom

In [239]:
df["Invoice"].str.replace("[0-9]","",regex=True).unique()
# we strip all digit number and replace with empty string
# unique show all distinct result

<StringArray>
['', 'C', 'A']
Length: 3, dtype: str

In [240]:
df[df["Invoice"].str.startswith("A")].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
299982,A563185,B,Adjust bad debt,1,12/8/2011 14:50,11062.06,NaN,United Kingdom
299983,A563186,B,Adjust bad debt,1,12/8/2011 14:51,-11062.06,NaN,United Kingdom
299984,A563187,B,Adjust bad debt,1,12/8/2011 14:52,-11062.06,NaN,United Kingdom

In [241]:
df[df["Invoice"].str.startswith("C")].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
141,C536379,D,Discount,-1,1/12/2010 9:41,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,1/12/2010 9:49,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,1/12/2010 10:24,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,1/12/2010 10:24,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,1/12/2010 10:24,0.29,17548.0,United Kingdom

In [242]:
df["StockCode"]=df["StockCode"].astype("str") # Use regex to find out anomaly
valid_stockcode = df["StockCode"].str.match("\\d{5}[a-zA-Z]*$") ==True 
anomalies_stockcode = df[~valid_stockcode]
print(anomalies_stockcode["StockCode"].unique())

<StringArray>
[        'POST',            'D',           'C2',          'DOT',
            'M', 'BANK CHARGES',            'S',    'AMAZONFEE',
     'DCGS0076',     'DCGS0003', 'gift_0001_40',     'DCGS0070',
            'm', 'gift_0001_50', 'gift_0001_30', 'gift_0001_20',
     'DCGS0055',     'DCGS0072',     'DCGS0074',     'DCGS0069',
     'DCGS0057',     'DCGSSBOY',    'DCGSSGIRL', 'gift_0001_10',
         'PADS',     'DCGS0004',     'DCGS0073',     'DCGS0071',
    'DCGS0066P',     'DCGS0068',     'DCGS0067',            'B',
         'CRUK']
Length: 33, dtype: str

In [243]:
print(anomalies_stockcode)

        Invoice StockCode Description  Quantity      InvoiceDate   Price  \
45       536370      POST     POSTAGE         3   1/12/2010 8:45   18.00
141     C536379         D    Discount        -1   1/12/2010 9:41   27.50
386      536403      POST     POSTAGE         1  1/12/2010 11:27   15.00
1123     536527      POST     POSTAGE         1  1/12/2010 13:04   18.00
1423     536540        C2    CARRIAGE         1  1/12/2010 14:05   50.00
...         ...       ...         ...       ...              ...     ...
541541  C581499         M      Manual        -1  9/12/2011 10:28  224.69
541730   581570      POST     POSTAGE         1  9/12/2011 11:59   18.00
541767   581574      POST     POSTAGE         2  9/12/2011 12:09   18.00
541768   581578      POST     POSTAGE         3  9/12/2011 12:16   18.00
541909   581587      POST     POSTAGE         1  9/12/2011 12:50   18.00

        Customer ID         Country
45          12583.0          France
141         14527.0  United Kingdom
386         12791.0     Netherlands
1123        12662.0         Germany
1423        14911.0            EIRE
...             ...             ...
541541      15498.0  United Kingdom
541730      12662.0         Germany
541767      12526.0         Germany
541768      12713.0         Germany
541909      12680.0          France

[2996 rows x 8 columns]

# Regex search in the StockCode column
StockCode have 3098 rows that are not 5 digit integral number  
Dive in deeper to figure out wheter include those row into the clustering or not

In [244]:
df[df["StockCode"].str.startswith("DOT")].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
1815,536544,DOT,DOTCOM POSTAGE,1,1/12/2010 14:32,569.77,NaN,United Kingdom
3041,536592,DOT,DOTCOM POSTAGE,1,1/12/2010 17:06,607.49,NaN,United Kingdom
5450,536862,DOT,DOTCOM POSTAGE,1,3/12/2010 11:13,254.43,NaN,United Kingdom
5545,536864,DOT,DOTCOM POSTAGE,1,3/12/2010 11:27,121.06,NaN,United Kingdom
5686,536865,DOT,DOTCOM POSTAGE,1,3/12/2010 11:28,498.47,NaN,United Kingdom

In [245]:
df[df["StockCode"].str.startswith("POST")].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
45,536370,POST,POSTAGE,3,1/12/2010 8:45,18.0,12583.0,France
386,536403,POST,POSTAGE,1,1/12/2010 11:27,15.0,12791.0,Netherlands
1123,536527,POST,POSTAGE,1,1/12/2010 13:04,18.0,12662.0,Germany
5095,536840,POST,POSTAGE,1,2/12/2010 18:27,18.0,12738.0,Germany
5258,536852,POST,POSTAGE,1,3/12/2010 9:51,18.0,12686.0,France

In [246]:
df[df["StockCode"].str.startswith("C2")].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
1423,536540,C2,CARRIAGE,1,1/12/2010 14:05,50.0,14911.0,EIRE
12119,537368,C2,CARRIAGE,1,6/12/2010 12:40,50.0,14911.0,EIRE
12452,537378,C2,CARRIAGE,1,6/12/2010 13:06,50.0,14911.0,EIRE
19975,537963,C2,CARRIAGE,1,9/12/2010 11:30,50.0,13369.0,United Kingdom
20016,538002,C2,CARRIAGE,1,9/12/2010 11:48,50.0,14932.0,Channel Islands

In [247]:
df[df["StockCode"].str.startswith("DCGS")].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
21326,538071,DCGS0076,SUNJAR LED NIGHT NIGHT LIGHT,1,9/12/2010 14:09,16.13,NaN,United Kingdom
24906,538349,DCGS0003,BOXED GLASS ASHTRAY,1,10/12/2010 14:59,2.51,NaN,United Kingdom
36460,539451,DCGS0003,BOXED GLASS ASHTRAY,1,17/12/2010 16:59,2.51,NaN,United Kingdom
39313,539631,DCGS0076,SUNJAR LED NIGHT NIGHT LIGHT,2,20/12/2010 15:03,16.13,NaN,United Kingdom
40052,539718,DCGS0070,CAMOUFLAGE DOG COLLAR,1,21/12/2010 13:06,12.72,NaN,United Kingdom

In [248]:
df[df["StockCode"].str.startswith("PADS")].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
157195,550193,PADS,PADS TO MATCH ALL CUSHIONS,1,15/4/2011 9:27,0.001,13952.0,United Kingdom
279045,561226,PADS,PADS TO MATCH ALL CUSHIONS,1,26/7/2011 10:13,0.001,15618.0,United Kingdom
358670,568158,PADS,PADS TO MATCH ALL CUSHIONS,1,25/9/2011 12:22,0.000,16133.0,United Kingdom
359871,568200,PADS,PADS TO MATCH ALL CUSHIONS,1,25/9/2011 14:58,0.001,16198.0,United Kingdom

In [249]:
df[df["StockCode"].str.startswith("M")].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
2239,536569,M,Manual,1,1/12/2010 15:35,1.25,16274.0,United Kingdom
2250,536569,M,Manual,1,1/12/2010 15:35,18.95,16274.0,United Kingdom
5685,536865,M,Manual,1,3/12/2010 11:28,2.55,NaN,United Kingdom
6798,536981,M,Manual,2,3/12/2010 14:26,0.85,14723.0,United Kingdom
7976,537077,M,Manual,12,5/12/2010 11:59,0.42,17062.0,United Kingdom

Identify each unique string of stock code 
|stock code|Description|Action on Clustering|
|----------|-----------|------|
|POST|postage|exclude|
|DOT|postage charge|exclude|
|C2|Carraige|exclude|
|DCGS|nun|exclude|
|PADS|padding|include|
|S|sample|exclude|
|M,m|manual transaction|exclude
|D|discount|exclude

# Data Cleaning

In [250]:
cleaned_df1 = df.copy()

In [251]:
cleaned_df1["Invoice"] = cleaned_df1["Invoice"].astype("str")

mask = (cleaned_df1["Invoice"].str.match("^\\d{6}$")==True)  # mask is use as filtering expression to filter unwanted invoice 

cleaned_df1 = cleaned_df1[mask]

cleaned_df1

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,1/12/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,1/12/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,1/12/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,1/12/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,1/12/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,9/12/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,9/12/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,9/12/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,9/12/2011 12:50,4.95,12680.0,France
541909,581587,POST,POSTAGE,1,9/12/2011 12:50,18.00,12680.0,France

In [252]:
cleaned_df1["StockCode"] = cleaned_df1["StockCode"].astype("str")

mask = (
    (cleaned_df1["StockCode"].str.match("^\\d{5}$") == True) # Condition 1
    | (cleaned_df1["StockCode"].str.match("^\\d{5}[a-zA-Z]+$") == True) # Condition 2
    | (cleaned_df1["StockCode"].str.match("^PADS$") == True) # Condition 3
)

cleaned_df1 = cleaned_df1[mask]

cleaned_df1

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,1/12/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,1/12/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,1/12/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,1/12/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,1/12/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,9/12/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,9/12/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,9/12/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,9/12/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,9/12/2011 12:50,4.95,12680.0,France

In [253]:
cleaned_df1 = cleaned_df1.drop_duplicates()

In [254]:
cleaned_df1.dropna(subset=["Customer ID"], inplace=True)

In [255]:
cleaned_df1.describe()

            Quantity          Price    Customer ID
count  391187.000000  391187.000000  391187.000000
mean       13.179541       2.874101   15295.085345
std       181.906477       4.284627    1710.353395
min         1.000000       0.000000   12346.000000
25%         2.000000       1.250000   13969.000000
50%         6.000000       1.950000   15158.000000
75%        12.000000       3.750000   16794.000000
max     80995.000000     649.500000   18287.000000

In [256]:
len(cleaned_df1[cleaned_df1["Price"]==0]) # To check how many 0 price in dataset

34

In [257]:
cleaned_df1[cleaned_df1["Price"]== 0] # To view the data with 0 price

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
9302,537197,22841,ROUND CAKE TIN VINTAGE GREEN,1,5/12/2010 14:02,0.0,12647.0,Germany
33576,539263,22580,ADVENT CALENDAR GINGHAM SACK,4,16/12/2010 14:36,0.0,16560.0,United Kingdom
40089,539722,22423,REGENCY CAKESTAND 3 TIER,10,21/12/2010 13:45,0.0,14911.0,EIRE
47068,540372,22090,PAPER BUNTING RETROSPOT,24,6/1/2011 16:41,0.0,13081.0,United Kingdom
47070,540372,22553,PLASTERS IN TIN SKULLS,24,6/1/2011 16:41,0.0,13081.0,United Kingdom
56674,541109,22168,ORGANISER WOOD ANTIQUE WHITE,1,13/1/2011 15:10,0.0,15107.0,United Kingdom
86789,543599,84535B,FAIRY CAKES NOTEBOOK A6 SIZE,16,10/2/2011 13:08,0.0,17560.0,United Kingdom
130188,547417,22062,CERAMIC BOWL WITH LOVE HEART DESIGN,36,23/3/2011 10:25,0.0,13239.0,United Kingdom
139453,548318,22055,MINI CAKE STAND HANGING STRAWBERY,5,30/3/2011 12:45,0.0,13113.0,United Kingdom
145208,548871,22162,HEART GARLAND RUSTIC PADDED,2,4/4/2011 14:42,0.0,14410.0,United Kingdom
157042,550188,22636,CHILDS BREAKFAST SET CIRCUS PARADE,1,14/4/2011 18:57,0.0,12457.0,Switzerland
187613,553000,47566,PARTY BUNTING,4,12/5/2011 15:21,0.0,17667.0,United Kingdom
198383,554037,22619,SET OF 6 SOLDIER SKITTLES,80,20/5/2011 14:13,0.0,12415.0,Australia
279323,561284,22167,OVAL WALL MIRROR DIAMANTE,1,26/7/2011 12:24,0.0,16818.0,United Kingdom
282912,561669,22960,JAM MAKING SET WITH JARS,11,28/7/2011 17:09,0.0,12507.0,Spain
298054,562973,23157,SET OF 6 NATIVITY MAGNETS,240,11/8/2011 11:42,0.0,14911.0,EIRE
314745,564651,23270,SET OF 2 CERAMIC PAINTED HEARTS,96,26/8/2011 14:19,0.0,14646.0,Netherlands
314746,564651,23268,SET OF 2 CERAMIC CHRISTMAS REINDEER,192,26/8/2011 14:19,0.0,14646.0,Netherlands
314747,564651,22955,36 FOIL STAR CAKE CASES,144,26/8/2011 14:19,0.0,14646.0,Netherlands
314748,564651,21786,POLKADOT RAIN HAT,144,26/8/2011 14:19,0.0,14646.0,Netherlands
358670,568158,PADS,PADS TO MATCH ALL CUSHIONS,1,25/9/2011 12:22,0.0,16133.0,United Kingdom
379913,569716,22778,GLASS CLOCHE SMALL,2,6/10/2011 8:17,0.0,15804.0,United Kingdom
420404,572893,21208,PASTEL COLOUR HONEYCOMB FAN,5,26/10/2011 14:36,0.0,18059.0,United Kingdom
436428,574138,23234,BISCUIT TIN VINTAGE CHRISTMAS,216,3/11/2011 11:26,0.0,12415.0,Australia
436597,574175,22065,CHRISTMAS PUDDING TRINKET POT,12,3/11/2011 11:47,0.0,14110.0,United Kingdom
439361,574469,22385,JUMBO BAG SPACEBOY DESIGN,12,4/11/2011 11:55,0.0,12431.0,Australia
446125,574879,22625,RED KITCHEN SCALES,2,7/11/2011 13:22,0.0,13014.0,United Kingdom
446793,574920,22899,CHILDREN'S APRON DOLLY GIRL,1,7/11/2011 16:34,0.0,13985.0,United Kingdom
446794,574920,23480,MINI LIGHTS WOODLAND MUSHROOMS,1,7/11/2011 16:34,0.0,13985.0,United Kingdom
454463,575579,22437,SET OF 9 BLACK SKULL BALLOONS,20,10/11/2011 11:49,0.0,13081.0,United Kingdom
454464,575579,22089,PAPER BUNTING VINTAGE PAISLEY,24,10/11/2011 11:49,0.0,13081.0,United Kingdom
479079,577129,22464,HANGING METAL HEART LANTERN,4,17/11/2011 19:52,0.0,15602.0,United Kingdom
480649,577314,23407,SET OF 2 TRAYS HOME SWEET HOME,2,18/11/2011 13:23,0.0,12444.0,Norway
502122,578841,84826,ASSTD DESIGN 3D PAPER STICKERS,12540,25/11/2011 15:57,0.0,13256.0,United Kingdom

In [258]:
cleaned_df1["Price"] = pd.to_numeric(cleaned_df1["Price"],errors="coerce") # convert the Price to numeric as it show the data type is string

In [259]:
cleaned_df1 = cleaned_df1[cleaned_df1["Price"] > 0] # To filter all unwanted 0

In [260]:
cleaned_df1 = cleaned_df1[cleaned_df1["Quantity"]>0] # TO filter all unwanted quantity with 0 or less than 0

In [261]:
cleaned_df1.describe()  # still got the 0 price

            Quantity          Price    Customer ID
count  391153.000000  391153.000000  391153.000000
mean       13.145207       2.874350   15295.171156
std       180.807141       4.284729    1710.334509
min         1.000000       0.001000   12346.000000
25%         2.000000       1.250000   13969.000000
50%         6.000000       1.950000   15159.000000
75%        12.000000       3.750000   16794.000000
max     80995.000000     649.500000   18287.000000

In [262]:
cleaned_df1.select_dtypes(include=["object"]).describe().T

C:\Users\User\AppData\Local\Temp\ipykernel_15708\3413266033.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cleaned_df1.select_dtypes(include=["object"]).describe().T

              count unique                                 top    freq
Invoice      391153  18402                              576339     541
StockCode    391153   3660                              85123A    2023
Description  391153   3872  WHITE HANGING HEART T-LIGHT HOLDER    2016
InvoiceDate  391153  17166                    14/11/2011 15:27     541
Country      391153     37                      United Kingdom  348875

In [263]:
cleaned_df1["Price"].min()  # it show that 0 is 0.001 still bigger than 0 so we cant remove the 0 at all

np.float64(0.001)

In [264]:
cleaned_df1[["Quantity","Price"]].describe()

            Quantity          Price
count  391153.000000  391153.000000
mean       13.145207       2.874350
std       180.807141       4.284729
min         1.000000       0.001000
25%         2.000000       1.250000
50%         6.000000       1.950000
75%        12.000000       3.750000
max     80995.000000     649.500000

# To record down how much data are loss during data cleaning that often ask by client

In [265]:
(len(df)-len(cleaned_df1))/len(df)

0.2781956413426584

In [266]:
len(cleaned_df1)/len(df)

0.7218043586573416

In [267]:
cleaned_df1.to_csv("C:\\Desktop\\Online retail UnsML k-mean analysis\\Artifact\\cleaned_df.csv",index=False)
print("succesfully save!")

succesfully save!

# 27.82% of datasets are filter out from the cleaned dataset 
- Contain Null number in Customer ID 
- Exclude all Cancellation Invoice ID 
- Exclude all Null number in Description
- Exclude all unwanted StockCode value

# EDA Report
- Original dataset shape = (541910,8)
- Cleaned dataset shape = (391153,8)
- Cleaned dataset data type = datetime64(1), float64(2), int64(1), object(3), str(1)