# Exploratory Data Analysis of online retail transacaction data

In [274]:
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats

In [230]:
source_link = "https://archive.ics.uci.edu/dataset/502/online+retail+ii"

In [231]:
df = pd.read_excel("C:\\Desktop\\Online retail UnsML k-mean analysis\\online_retail_II.xlsx")
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

# Data Exploration

walk through each columns of data and check the data details before futher feature engeering

In [232]:
df.info()
df.shape

<class 'pandas.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      525461 non-null  object
 1   StockCode    525461 non-null  object
 2   Description  522533 non-null  object
 3   Quantity     525461 non-null  int64
 4   InvoiceDate  525461 non-null  datetime64[us]
 5   Price        525461 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      525461 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 32.1+ MB

(525461, 8)

In [233]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
Quantity,525461.0,10.337667,-9600.0,1.0,3.0,10.0,19152.0,107.42411
InvoiceDate,525461,2010-06-28 11:37:36.845018,2009-12-01 07:45:00,2010-03-21 12:20:00,2010-07-06 09:51:00,2010-10-15 12:45:00,2010-12-09 20:01:00,NaN
Price,525461.0,4.688834,-53594.36,1.25,2.1,4.21,25111.09,146.126914
Customer ID,417534.0,15360.645478,12346.0,13983.0,15311.0,16799.0,18287.0,1680.811316

In [234]:
df.select_dtypes(include=["object"]).describe().T

C:\Users\User\AppData\Local\Temp\ipykernel_11968\2317286653.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include=["object"]).describe().T

              count unique                                 top    freq
Invoice      525461  28816                              537434     675
StockCode    525461   4632                              85123A    3516
Description  522533   4681  WHITE HANGING HEART T-LIGHT HOLDER    3549
Country      525461     40                      United Kingdom  485852

In [235]:
print(df.duplicated().sum())

6865

In [236]:
df[df.duplicated(keep='first')].sort_values(by=df.columns.tolist())

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
391,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
394,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
...,...,...,...,...,...,...,...,...
374743,C525550,22158,3 HEARTS HANGING DECORATION RUSTIC,-8,2010-10-05 19:31:00,2.95,15270.0,United Kingdom
408173,C528451,22179,SET 10 LIGHTS NIGHT OWL,-1,2010-10-22 11:23:00,6.75,12986.0,United Kingdom
420572,C529606,22728,ALARM CLOCK BAKELIKE PINK,-12,2010-10-29 10:28:00,3.75,17396.0,United Kingdom
483401,C534698,22119,PEACE WOODEN BLOCK LETTERS,-1,2010-11-23 15:59:00,6.95,16242.0,United Kingdom
501990,C536210,22838,3 TIER CAKE TIN RED AND CREAM,-1,2010-11-30 13:27:00,14.95,17402.0,United Kingdom

In [237]:
df[df.duplicated(keep=False)].sort_values(by=df.columns.tolist())
# This keep = False shows 13,283 rows that each have at least one duplicate,
# some row may appear more than twice

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
379,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
391,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
...,...,...,...,...,...,...,...,...
420572,C529606,22728,ALARM CLOCK BAKELIKE PINK,-12,2010-10-29 10:28:00,3.75,17396.0,United Kingdom
483397,C534698,22119,PEACE WOODEN BLOCK LETTERS,-1,2010-11-23 15:59:00,6.95,16242.0,United Kingdom
483401,C534698,22119,PEACE WOODEN BLOCK LETTERS,-1,2010-11-23 15:59:00,6.95,16242.0,United Kingdom
501989,C536210,22838,3 TIER CAKE TIN RED AND CREAM,-1,2010-11-30 13:27:00,14.95,17402.0,United Kingdom
501990,C536210,22838,3 TIER CAKE TIN RED AND CREAM,-1,2010-11-30 13:27:00,14.95,17402.0,United Kingdom

In [238]:
print("Null number:\n",df.isnull().sum())

Null number:
 Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107927
Country             0
dtype: int64

In [239]:
df[df["Customer ID"].isnull()].head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.00,NaN,United Kingdom
283,489463,71477,short,-240,2009-12-01 10:52:00,0.00,NaN,United Kingdom
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.00,NaN,United Kingdom
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.00,NaN,United Kingdom
577,489525,85226C,BLUE PULL BACK RACING CAR,1,2009-12-01 11:49:00,0.55,NaN,United Kingdom
578,489525,85227,SET/6 3D KIT CARDS FOR KIDS,1,2009-12-01 11:49:00,0.85,NaN,United Kingdom
1055,489548,22271,FELTCRAFT DOLL ROSIE,1,2009-12-01 12:32:00,2.95,NaN,United Kingdom
1056,489548,22254,FELT TOADSTOOL LARGE,12,2009-12-01 12:32:00,1.25,NaN,United Kingdom
1057,489548,22273,FELTCRAFT DOLL MOLLY,3,2009-12-01 12:32:00,2.95,NaN,United Kingdom
1058,489548,22195,LARGE HEART MEASURING SPOONS,1,2009-12-01 12:32:00,1.65,NaN,United Kingdom

In [240]:
df[df["Description"].isnull()].head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0,NaN,United Kingdom
3114,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0,NaN,United Kingdom
3161,489659,21350,NaN,230,2009-12-01 17:39:00,0.0,NaN,United Kingdom
3731,489781,84292,NaN,17,2009-12-02 11:45:00,0.0,NaN,United Kingdom
4296,489806,18010,NaN,-770,2009-12-02 12:42:00,0.0,NaN,United Kingdom
4566,489821,85049G,NaN,-240,2009-12-02 13:25:00,0.0,NaN,United Kingdom
6378,489882,35751C,NaN,12,2009-12-02 16:22:00,0.0,NaN,United Kingdom
6555,489898,79323G,NaN,954,2009-12-03 09:40:00,0.0,NaN,United Kingdom
6576,489901,21098,NaN,-200,2009-12-03 09:47:00,0.0,NaN,United Kingdom
6581,489903,21166,NaN,48,2009-12-03 09:57:00,0.0,NaN,United Kingdom

In [241]:
df[df["Quantity"]<0].head(10)
# quantity with <0 means cancel as the invoice number start with c

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,2009-12-01 10:33:00,1.65,16321.0,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,2009-12-01 10:33:00,4.25,16321.0,Australia
181,C489449,21896,POTTING SHED TWINE,-6,2009-12-01 10:33:00,2.10,16321.0,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
183,C489449,21871,SAVE THE PLANET MUG,-12,2009-12-01 10:33:00,1.25,16321.0,Australia
184,C489449,84946,ANTIQUE SILVER TEA GLASS ETCHED,-12,2009-12-01 10:33:00,1.25,16321.0,Australia
185,C489449,84970S,HANGING HEART ZINC T-LIGHT HOLDER,-24,2009-12-01 10:33:00,0.85,16321.0,Australia
186,C489449,22090,PAPER BUNTING RETRO SPOTS,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
196,C489459,90200A,PURPLE SWEETHEART BRACELET,-3,2009-12-01 10:44:00,4.25,17592.0,United Kingdom

In [242]:
df["Invoice"] = df["Invoice"].astype("str") # Use regex to catch anomaly in columns , regex only can run on str so convert to str first
df[df["Invoice"].str.match("^\\d{6}$")==False] # catch anomaly 
# these 2 line are to show the invoice with c letterstand for cancellation

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,2009-12-01 10:33:00,1.65,16321.0,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,2009-12-01 10:33:00,4.25,16321.0,Australia
181,C489449,21896,POTTING SHED TWINE,-6,2009-12-01 10:33:00,2.10,16321.0,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
...,...,...,...,...,...,...,...,...
524695,C538123,22956,36 FOIL HEART CAKE CASES,-2,2010-12-09 15:41:00,2.10,12605.0,Germany
524696,C538124,M,Manual,-4,2010-12-09 15:43:00,0.50,15329.0,United Kingdom
524697,C538124,22699,ROSES REGENCY TEACUP AND SAUCER,-1,2010-12-09 15:43:00,2.95,15329.0,United Kingdom
524698,C538124,22423,REGENCY CAKESTAND 3 TIER,-1,2010-12-09 15:43:00,12.75,15329.0,United Kingdom
525282,C538164,35004B,SET OF 3 BLACK FLYING DUCKS,-1,2010-12-09 17:32:00,1.95,14031.0,United Kingdom

In [243]:
df["Invoice"].str.replace("[0-9]","",regex=True).unique()
# we strip all digit number and replace with empty string
# unique show all distinct result

<StringArray>
['', 'C', 'A']
Length: 3, dtype: str

In [244]:
df[df["Invoice"].str.startswith("A")].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
179403,A506401,B,Adjust bad debt,1,2010-04-29 13:36:00,-53594.36,NaN,United Kingdom
276274,A516228,B,Adjust bad debt,1,2010-07-19 11:24:00,-44031.79,NaN,United Kingdom
403472,A528059,B,Adjust bad debt,1,2010-10-20 12:04:00,-38925.87,NaN,United Kingdom

In [245]:
df[df["Invoice"].str.startswith("C")].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,2009-12-01 10:33:00,1.65,16321.0,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,2009-12-01 10:33:00,4.25,16321.0,Australia
181,C489449,21896,POTTING SHED TWINE,-6,2009-12-01 10:33:00,2.10,16321.0,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2009-12-01 10:33:00,2.95,16321.0,Australia

In [246]:
df["StockCode"]=df["StockCode"].astype("str") # Use regex to find out anomaly
valid_stockcode = df["StockCode"].str.match("\\d{5}[a-zA-Z]*$") ==True 
anomalies_stockcode = df[~valid_stockcode]
print(anomalies_stockcode["StockCode"].unique())

<StringArray>
[        'POST',            'D',     'DCGS0058',     'DCGS0068',
          'DOT',            'M',     'DCGS0004',     'DCGS0076',
           'C2', 'BANK CHARGES',     'DCGS0003',      'TEST001',
 'gift_0001_80',     'DCGS0072', 'gift_0001_20',     'DCGS0044',
      'TEST002', 'gift_0001_10', 'gift_0001_50',    'DCGS0066N',
 'gift_0001_30',         'PADS',       'ADJUST', 'gift_0001_40',
 'gift_0001_60', 'gift_0001_70', 'gift_0001_90',    'DCGSSGIRL',
     'DCGS0006',     'DCGS0016',     'DCGS0027',     'DCGS0036',
     'DCGS0039',     'DCGS0060',     'DCGS0056',     'DCGS0059',
         'GIFT',     'DCGSLBOY',            'm',     'DCGS0053',
     'DCGS0062',     'DCGS0037',     'DCGSSBOY',    'DCGSLGIRL',
            'S',     'DCGS0069',     'DCGS0070',     'DCGS0075',
            'B',     'DCGS0041',      'ADJUST2',      '47503J ',
           'C3',       'SP1002',    'AMAZONFEE']
Length: 55, dtype: str

In [247]:
print(anomalies_stockcode)

        Invoice StockCode     Description  Quantity         InvoiceDate  \
89       489439      POST         POSTAGE         3 2009-12-01 09:28:00
126      489444      POST         POSTAGE         1 2009-12-01 09:55:00
173      489447      POST         POSTAGE         1 2009-12-01 10:10:00
625      489526      POST         POSTAGE         6 2009-12-01 11:50:00
735     C489535         D        Discount        -1 2009-12-01 12:11:00
...         ...       ...             ...       ...                 ...
524776   538147         M          Manual         1 2010-12-09 16:11:00
524887   538148       DOT  DOTCOM POSTAGE         1 2010-12-09 16:26:00
525000   538149       DOT  DOTCOM POSTAGE         1 2010-12-09 16:27:00
525126   538153       DOT  DOTCOM POSTAGE         1 2010-12-09 16:31:00
525147   538154       DOT  DOTCOM POSTAGE         1 2010-12-09 16:35:00

         Price  Customer ID         Country
89       18.00      12682.0          France
126     141.00      12636.0             USA
173     130.00      12362.0         Belgium
625      18.00      12533.0         Germany
735       9.00      15299.0  United Kingdom
...        ...          ...             ...
524776   15.00      13090.0  United Kingdom
524887  547.32          NaN  United Kingdom
525000  620.68          NaN  United Kingdom
525126  822.94          NaN  United Kingdom
525147   85.79          NaN  United Kingdom

[3098 rows x 8 columns]

# Regex search in the StockCode column
StockCode have 3098 rows that are not 5 digit integral number  
Dive in deeper to figure out wheter include those row into the clustering or not

In [248]:
df[df["StockCode"].str.startswith("DOT")].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
2379,489597,DOT,DOTCOM POSTAGE,1,2009-12-01 14:28:00,647.19,NaN,United Kingdom
2539,489600,DOT,DOTCOM POSTAGE,1,2009-12-01 14:43:00,55.96,NaN,United Kingdom
2551,489601,DOT,DOTCOM POSTAGE,1,2009-12-01 14:44:00,68.39,NaN,United Kingdom
2571,489602,DOT,DOTCOM POSTAGE,1,2009-12-01 14:45:00,59.35,NaN,United Kingdom
2619,489603,DOT,DOTCOM POSTAGE,1,2009-12-01 14:46:00,42.39,NaN,United Kingdom

In [249]:
df[df["StockCode"].str.startswith("POST")].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
89,489439,POST,POSTAGE,3,2009-12-01 09:28:00,18.00,12682.0,France
126,489444,POST,POSTAGE,1,2009-12-01 09:55:00,141.00,12636.0,USA
173,489447,POST,POSTAGE,1,2009-12-01 10:10:00,130.00,12362.0,Belgium
625,489526,POST,POSTAGE,6,2009-12-01 11:50:00,18.00,12533.0,Germany
927,C489538,POST,POSTAGE,-1,2009-12-01 12:18:00,9.58,15796.0,United Kingdom

In [250]:
df[df["StockCode"].str.startswith("C2")].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
9292,490127,C2,CARRIAGE,1,2009-12-03 18:13:00,50.0,14156.0,EIRE
14481,490541,C2,CARRIAGE,1,2009-12-07 09:25:00,50.0,NaN,EIRE
14502,490542,C2,CARRIAGE,1,2009-12-07 09:42:00,50.0,14911.0,EIRE
19541,490998,C2,CARRIAGE,1,2009-12-08 17:24:00,50.0,16253.0,United Kingdom
22803,491160,C2,CARRIAGE,1,2009-12-10 10:29:00,50.0,14911.0,EIRE

In [251]:
df[df["StockCode"].str.startswith("DCGS")].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
2377,489597,DCGS0058,MISO PRETTY GUM,1,2009-12-01 14:28:00,0.83,NaN,United Kingdom
2378,489597,DCGS0068,DOGS NIGHT COLLAR,1,2009-12-01 14:28:00,8.65,NaN,United Kingdom
8371,490074,DCGS0004,HAYNES CAMPER SHOULDER BAG,1,2009-12-03 14:39:00,17.35,NaN,United Kingdom
8372,490074,DCGS0058,MISO PRETTY GUM,1,2009-12-03 14:39:00,0.83,NaN,United Kingdom
8373,490074,DCGS0076,SUNJAR LED NIGHT NIGHT LIGHT,1,2009-12-03 14:39:00,16.48,NaN,United Kingdom

In [252]:
df[df["StockCode"].str.startswith("PADS")].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
62299,494914,PADS,PADS TO MATCH ALL CUSHIONS,1,2010-01-19 17:04:00,0.001,16705.0,United Kingdom
74731,496222,PADS,PADS TO MATCH ALL CUSHIONS,1,2010-01-29 13:53:00,0.001,13583.0,United Kingdom
77702,496473,PADS,PADS TO MATCH ALL CUSHIONS,1,2010-02-01 15:38:00,0.001,17350.0,United Kingdom
79794,496643,PADS,PADS TO MATCH ALL CUSHIONS,1,2010-02-03 11:58:00,0.001,13408.0,United Kingdom
90798,497935,PADS,PADS TO MATCH ALL CUSHIONS,1,2010-02-15 10:47:00,0.001,13408.0,United Kingdom

In [253]:
df[df["StockCode"].str.startswith("M")].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
2697,489609,M,Manual,1,2009-12-01 14:50:00,4.00,NaN,United Kingdom
3053,C489651,M,Manual,-1,2009-12-01 16:48:00,5.10,17804.0,United Kingdom
5897,C489859,M,Manual,-1,2009-12-02 14:45:00,69.57,NaN,United Kingdom
9259,C490126,M,Manual,-1,2009-12-03 18:12:00,5.95,15884.0,United Kingdom
9307,C490129,M,Manual,-1,2009-12-03 18:26:00,1998.49,15482.0,United Kingdom

Identify each unique string of stock code 
|stock code|Description|Action on Clustering|
|----------|-----------|------|
|POST|postage|exclude|
|DOT|postage charge|exclude|
|C2|Carraige|exclude|
|DCGS|nun|exclude|
|PADS|padding|include|
|S|sample|exclude|
|M,m|manual transaction|exclude
|D|discount|exclude

# Data Cleaning

In [254]:
cleaned_df1 = df.copy()

In [255]:
cleaned_df1["Invoice"] = cleaned_df1["Invoice"].astype("str")

mask = (cleaned_df1["Invoice"].str.match("^\\d{6}$")==True)  # mask is use as filtering expression to filter unwanted invoice 

cleaned_df1 = cleaned_df1[mask]

cleaned_df1

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
525456,538171,22271,FELTCRAFT DOLL ROSIE,2,2010-12-09 20:01:00,2.95,17530.0,United Kingdom
525457,538171,22750,FELTCRAFT PRINCESS LOLA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525458,538171,22751,FELTCRAFT PRINCESS OLIVIA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525459,538171,20970,PINK FLORAL FELTCRAFT SHOULDER BAG,2,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525460,538171,21931,JUMBO STORAGE BAG SUKI,2,2010-12-09 20:01:00,1.95,17530.0,United Kingdom

In [270]:
cleaned_df1["StockCode"] = cleaned_df1["StockCode"].astype("str")

mask = (
    (cleaned_df1["StockCode"].str.match("^\\d{5}$") == True) # Condition 1
    | (cleaned_df1["StockCode"].str.match("^\\d{5}{a-zA-Z}+$") == True) # Condition 2
    | (cleaned_df1["StockCode"].str.match("^PADS$") == True) # Condition 3
)

cleaned_df1 = cleaned_df1[mask]

cleaned_df1

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
5,489434,22064,PINK DOUGHNUT TRINKET POT,24,2009-12-01 07:45:00,1.65,13085.0,United Kingdom
6,489434,21871,SAVE THE PLANET MUG,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
525456,538171,22271,FELTCRAFT DOLL ROSIE,2,2010-12-09 20:01:00,2.95,17530.0,United Kingdom
525457,538171,22750,FELTCRAFT PRINCESS LOLA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525458,538171,22751,FELTCRAFT PRINCESS OLIVIA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525459,538171,20970,PINK FLORAL FELTCRAFT SHOULDER BAG,2,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525460,538171,21931,JUMBO STORAGE BAG SUKI,2,2010-12-09 20:01:00,1.95,17530.0,United Kingdom

In [257]:
cleaned_df1.dropna(subset=["Customer ID"], inplace=True)

In [258]:
cleaned_df1.describe()

            Quantity                 InvoiceDate          Price    Customer ID
count  350943.000000                      350943  350943.000000  350943.000000
mean       13.699606  2010-07-05 17:09:34.748548       2.979564   15360.244439
min         1.000000         2009-12-01 07:45:00       0.000000   12346.000000
25%         2.000000         2010-03-31 17:29:00       1.250000   13985.000000
50%         5.000000         2010-07-18 13:42:00       1.950000   15311.000000
75%        12.000000         2010-10-17 14:26:00       3.750000   16797.000000
max     19152.000000         2010-12-09 20:01:00     295.000000   18287.000000
std       100.074815                         NaN       4.424673    1678.202935

In [259]:
len(cleaned_df1[cleaned_df1["Price"]==0]) # To check how many 0 price in dataset

27

In [260]:
cleaned_df1[cleaned_df1["Price"]== 0] # To view the data with 0 price

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
4674,489825,22076,6 RIBBONS EMPIRE,12,2009-12-02 13:34:00,0.0,16126.0,United Kingdom
6781,489998,48185,DOOR MAT FAIRY CAKE,2,2009-12-03 11:19:00,0.0,15658.0,United Kingdom
18738,490961,22065,CHRISTMAS PUDDING TRINKET POT,1,2009-12-08 15:25:00,0.0,14108.0,United Kingdom
18739,490961,22142,CHRISTMAS CRAFT WHITE FAIRY,12,2009-12-08 15:25:00,0.0,14108.0,United Kingdom
32916,492079,85042,ANTIQUE LILY FAIRY LIGHTS,8,2009-12-15 13:49:00,0.0,15070.0,United Kingdom
40101,492760,21143,ANTIQUE GLASS HEART DECORATION,12,2009-12-18 14:22:00,0.0,18071.0,United Kingdom
47126,493761,79320,FLAMINGO LIGHTS,24,2010-01-06 14:54:00,0.0,14258.0,United Kingdom
48342,493899,22355,"CHARLOTTE BAG , SUKI DESIGN",10,2010-01-08 10:43:00,0.0,12417.0,Belgium
57619,494607,21533,RETRO SPOT LARGE MILK JUG,12,2010-01-15 12:43:00,0.0,16858.0,United Kingdom
111348,500073,21662,VINTAGE GLASS COFFEE CADDY,1,2010-03-04 11:44:00,0.0,13047.0,United Kingdom
149201,503585,22459,CAST IRON HOOK GARDEN TROWEL,8,2010-04-01 17:13:00,0.0,13047.0,United Kingdom
149202,503585,22458,CAST IRON HOOK GARDEN FORK,8,2010-04-01 17:13:00,0.0,13047.0,United Kingdom
166143,505083,22376,AIRLINE BAG VINTAGE JET SET WHITE,1,2010-04-20 09:56:00,0.0,12623.0,Germany
232526,511902,21765,HANGING METAL BIRD BATH,1,2010-06-11 11:12:00,0.0,12748.0,United Kingdom
240455,512609,20914,SET/5 RED SPOTTY LID GLASS BOWLS,2,2010-06-17 10:12:00,0.0,14045.0,United Kingdom
248583,513416,22423,REGENCY CAKESTAND 3 TIER,5,2010-06-24 12:34:00,0.0,13089.0,United Kingdom
276858,516304,22690,DOORMAT HOME SWEET HOME BLUE,6,2010-07-19 13:13:00,0.0,14025.0,United Kingdom
296375,518231,22472,TV DINNER TRAY DOLLY GIRL,9,2010-08-05 15:28:00,0.0,12471.0,Germany
327801,521375,22202,MILK PAN PINK RETROSPOT,3,2010-09-05 11:58:00,0.0,12647.0,Germany
364333,524701,22218,CAKE STAND LACE WHITE,2,2010-09-30 12:19:00,0.0,17667.0,United Kingdom
392008,527084,22630,DOLLY GIRL LUNCH BOX,64,2010-10-14 15:33:00,0.0,14646.0,Netherlands
400047,527696,22121,NOEL WOODEN BLOCK LETTERS,1,2010-10-18 15:13:00,0.0,13554.0,United Kingdom
439309,531361,21843,RED RETROSPOT CAKE STAND,2,2010-11-07 14:26:00,0.0,12820.0,United Kingdom
453705,532470,22624,IVORY KITCHEN SCALES,2,2010-11-12 11:41:00,0.0,12647.0,Germany
471775,533822,22846,BREAD BIN DINER STYLE RED,1,2010-11-19 09:40:00,0.0,12647.0,Germany
471776,533822,22845,VINTAGE CREAM CAT FOOD CONTAINER,1,2010-11-19 09:40:00,0.0,12647.0,Germany
512240,537197,22841,ROUND CAKE TIN VINTAGE GREEN,1,2010-12-05 14:02:00,0.0,12647.0,Germany

In [261]:
cleaned_df1["Price"] = pd.to_numeric(cleaned_df1["Price"],errors="coerce") # convert the Price to numeric as it show the data type is string

In [262]:
cleaned_df1 = cleaned_df1[cleaned_df1["Price"] > 0] # To filter all unwanted 0

In [263]:
cleaned_df1.describe()  # still got the 0 price

            Quantity                 InvoiceDate          Price    Customer ID
count  350916.000000                      350916  350916.000000  350916.000000
mean       13.700059  2010-07-05 17:14:15.798310       2.979794   15360.352694
min         1.000000         2009-12-01 07:45:00       0.001000   12346.000000
25%         2.000000         2010-03-31 17:29:00       1.250000   13985.000000
50%         5.000000         2010-07-18 13:42:00       1.950000   15311.000000
75%        12.000000         2010-10-17 14:26:00       3.750000   16797.000000
max     19152.000000         2010-12-09 20:01:00     295.000000   18287.000000
std       100.078594                         NaN       4.424766    1678.162970

In [264]:
cleaned_df1.select_dtypes(include=["object"]).describe().T

C:\Users\User\AppData\Local\Temp\ipykernel_11968\3413266033.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cleaned_df1.select_dtypes(include=["object"]).describe().T

              count unique                       top    freq
Invoice      350916  18591                    531382     240
StockCode    350916   2725                     22423    1705
Description  350916   3100  REGENCY CAKESTAND 3 TIER    1705
Country      350916     37            United Kingdom  318900

In [265]:
cleaned_df1["Price"].min()  # it show that 0 is 0.001 still bigger than 0 so we cant remove the 0 at all

np.float64(0.001)

# To record down how much data are loss during data cleaning that often ask by client

In [266]:
(len(df)-len(cleaned_df1))/len(df)

0.33217498539377804

In [267]:
len(cleaned_df1)/len(df)

0.667825014606222

In [269]:
cleaned_df1.to_csv("cleaned_online_retail.csv",index=False)
print("succesfully save!")

succesfully save!

# 33.21% of datasets are filter out from the cleaned dataset 
- Contain Null number in Customer ID 
- Exclude all Cancellation Invoice ID 
- Exclude all Null number in Description
- Exclude all unwanted StockCode value

In [272]:
cleaned_df1[["Quantity","Price"]].describe()

            Quantity          Price
count  350916.000000  350916.000000
mean       13.700059       2.979794
std       100.078594       4.424766
min         1.000000       0.001000
25%         2.000000       1.250000
50%         5.000000       1.950000
75%        12.000000       3.750000
max     19152.000000     295.000000

# EDA Report
- Original dataset shape = (5254618,8)
- Cleaned dataset shape = (350916,8)
- Cleaned dataset data type = datetime64(1), float64(2), int64(1), object(3), str(1)